function [time, Vce, Ic] = importCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, VCE, IC] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [TIME, VCE, IC] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [time, Vce, Ic] = importfile(filename, [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Apr-2025 10:53:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["time", "Vce", "Ic"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
time = tbl.time;
Vce = tbl.Vce;
Ic = tbl.Ic;
end